name: Pre-commit checks

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==24.3.0
          pip install mypy==1.9.0
          pip install isort
          pip install ruff==0.3.3

      - name: Run black
        run: black --check .

      - name: Run mypy
        run: mypy .

      - name: Run isort
        run: isort --check --profile=black .

      - name: Run ruff
        run: ruff .

      - name: Check if any checks failed
        if: failure()
        run: echo "Some pre-commit checks have failed. Please run 'pre-commit run --all-files' locally and fix the issues."

      - name: Fail the job if any checks failed
        if: failure()
        run: exit 1
