name: Pre-commit checks

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==24.3.0
          pip install mypy==1.9.0
          pip install isort
          pip install ruff==0.3.3
          mypy --install-types

      - name: Run black
        id: black
        run: black --check .
        continue-on-error: true

      - name: Run mypy
        id: mypy
        run: mypy .
        continue-on-error: true

      - name: Run isort
        id: isort
        run: isort --check --profile=black .
        continue-on-error: true

      - name: Run ruff
        id: ruff
        run: ruff .
        continue-on-error: true

      - name: Check if any checks failed
        if: failure()
        run: echo "Some pre-commit checks have failed. Please run 'pre-commit run --all-files' locally and fix the issues."

      - name: Set job status
        if: failure()
        run: exit 1

      - name: Final status check
        if: success()
        run: echo "All pre-commit checks passed successfully."
